import { useMemo, useState } from 'react'
import { AlertPanel } from '../../components/common/AlertPanel'
import { DateRangePicker } from '../../components/common/DateRangePicker'
import { DepartmentBadge } from '../../components/common/DepartmentBadge'
import { FilterBar } from '../../components/common/FilterBar'
import { PageHeader } from '../../components/common/PageHeader'
import { PriorityBadge } from '../../components/common/PriorityBadge'
import { SearchInput } from '../../components/common/SearchInput'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useDepartmentWorkspace } from '../../hooks/useDepartmentWorkspace'
import { DepartmentTaskDrawer } from './DepartmentTaskDrawer'
import { DataTable } from '../../components/common/DataTable'

export function DepartmentMaintenancePage() { const { tasks, department, isMock, error, refresh } = useDepartmentWorkspace(); const [search, setSearch] = useState(''); const [priority, setPriority] = useState('ALL'); const [severity, setSeverity] = useState('ALL'); const [status, setStatus] = useState('ALL'); const [overdue, setOverdue] = useState('ALL'); const [dates, setDates] = useState({ from: '', to: '' }); const [selected, setSelected] = useState(null)
  const filtered = useMemo(() => tasks.filter((task) => `${task.id} ${task.asset} ${task.section}`.toLowerCase().includes(search.toLowerCase())).filter((task) => priority === 'ALL' || task.priority === priority).filter((task) => severity === 'ALL' || task.severity === severity).filter((task) => status === 'ALL' || task.status === status).filter((task) => overdue === 'ALL' || (overdue === 'YES' ? task.status === 'Overdue' || task.dueDate < '2026-09-07' : task.status !== 'Overdue' && task.dueDate >= '2026-09-07')).filter((task) => !dates.from || task.dueDate >= dates.from).filter((task) => !dates.to || task.dueDate <= dates.to), [tasks, search, priority, severity, status, overdue, dates])
  const columns = [{ key: 'priority', label: 'Priority', render: (row) => <PriorityBadge value={row.priority} /> }, { key: 'severity', label: 'Severity', render: (row) => <PriorityBadge value={row.severity} /> }, { key: 'criticality', label: 'Criticality', render: (row) => <PriorityBadge value={row.criticality} /> }, { key: 'overdue', label: 'Overdue', render: (row) => <StatusBadge tone={row.status === 'Overdue' ? 'critical' : 'low'}>{row.status === 'Overdue' ? 'Overdue' : 'On track'}</StatusBadge> }, { key: 'dueDate', label: 'Due date' }, { key: 'section', label: 'Section' }, { key: 'asset', label: 'Asset', render: (row) => <><strong className="table-primary">{row.asset}</strong><span className="table-secondary">{row.assetCode}</span></> }, { key: 'department', label: 'Department', render: (row) => <DepartmentBadge department={row.department} /> }, { key: 'action', label: 'Action', render: (row) => <button className="text-button" onClick={() => setSelected(row)}>Details</button> }]
  return <><PageHeader eyebrow={`${department} / MAINTENANCE`} title="Maintenance queue" description="Filter department work by urgency, asset condition and schedule readiness." actions={<StatusBadge tone={isMock ? 'demo' : 'low'}>{isMock ? 'Demo data' : 'Live API'}</StatusBadge>} />{error && !isMock && <AlertPanel tone="warning" title="Maintenance data unavailable" description={error.message} action={<button className="text-button" onClick={refresh}>Retry</button>} />}<FilterBar onReset={() => { setSearch(''); setPriority('ALL'); setSeverity('ALL'); setStatus('ALL'); setOverdue('ALL'); setDates({ from: '', to: '' }) }}><SearchInput value={search} onChange={setSearch} placeholder="Search task, asset or section" /><select className="filter-control" value={priority} onChange={(event) => setPriority(event.target.value)}><option value="ALL">All priorities</option><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select><select className="filter-control" value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="ALL">All severity</option><option>High</option><option>Medium</option><option>Low</option></select><select className="filter-control" value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option><option>Assigned</option><option>Scheduled</option><option>Unscheduled</option><option>Overdue</option></select><select className="filter-control" value={overdue} onChange={(event) => setOverdue(event.target.value)}><option value="ALL">Overdue: all</option><option value="YES">Overdue only</option><option value="NO">Not overdue</option></select><DateRangePicker from={dates.from} to={dates.to} onChange={setDates} /></FilterBar><DataTable columns={columns} rows={filtered} emptyMessage="No tasks match the current department filters." /><DepartmentTaskDrawer task={selected} onClose={() => setSelected(null)} /></> }
