import { AlertTriangle, CalendarClock, ClipboardCheck, Clock3, FileClock, ListTodo } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AlertPanel } from '../../components/common/AlertPanel'
import { DepartmentBadge } from '../../components/common/DepartmentBadge'
import { KpiCard } from '../../components/common/KpiCard'
import { PageHeader } from '../../components/common/PageHeader'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useDepartmentWorkspace } from '../../hooks/useDepartmentWorkspace'

const today = '2026-09-07'
export function DepartmentHomePage() { const { tasks, blocks, department, isMock, error, refresh } = useDepartmentWorkspace(); const navigate = useNavigate(); const critical = tasks.filter((task) => ['critical', 'high'].includes(String(task.priority).toLowerCase())); const overdue = tasks.filter((task) => task.status === 'Overdue' || task.dueDate < today); const scheduled = tasks.filter((task) => ['scheduled', 'in progress'].includes(String(task.status).toLowerCase())); const unscheduled = tasks.filter((task) => String(task.status).toLowerCase().includes('unscheduled'))
  return <><PageHeader eyebrow={`${department} / DEPARTMENT PLANNING`} title={`${department} planning desk`} description="Coordinate maintenance priorities, assets and the next viable maintenance block." actions={<button className="primary-button" onClick={() => navigate('/department/block-requests')}><CalendarClock size={16} /> Create block request</button>} />{isMock && <AlertPanel tone="info" title="Department demo data is active" description={`Showing isolated ${department} fixtures. Connect VITE_API_BASE_URL to replace them with backend data.`} />}{error && !isMock && <AlertPanel tone="warning" title="Live department data unavailable" description={error.message} action={<button className="text-button" onClick={refresh}>Retry</button>} />}<div className="kpi-grid"><KpiCard label="Total tasks" value={tasks.length} detail="Current department scope" tone="blue" icon={ListTodo} /><KpiCard label="Critical tasks" value={critical.length} detail="Priority attention" tone="red" icon={AlertTriangle} /><KpiCard label="Overdue tasks" value={overdue.length} detail="Requires escalation" tone="amber" icon={Clock3} /><KpiCard label="Pending block requests" value={blocks.filter((block) => String(block.status).toLowerCase().includes('pending')).length} detail="Awaiting review" tone="blue" icon={FileClock} /><KpiCard label="Scheduled tasks" value={scheduled.length} detail="Planned work" tone="green" icon={CalendarClock} /><KpiCard label="Unscheduled tasks" value={unscheduled.length} detail="Needs a window" tone="amber" icon={ClipboardCheck} /></div><div className="department-overview-grid"><section className="field-panel"><div className="panel-heading"><div><p className="eyebrow">SCOPE</p><h2>Department context</h2></div><DepartmentBadge department={department} /></div><div className="department-context"><strong>{department === 'ENGINEERING' ? 'Engineering maintenance' : department === 'TRD' ? 'Traction / OHE maintenance' : 'Signal & telecom maintenance'}</strong><p>All queue, asset and planning views are scoped to the selected department from the demo session.</p><button className="text-button" onClick={() => navigate('/department/maintenance')}>Open maintenance queue <ClipboardCheck size={15} /></button></div></section><section className="field-panel"><div className="panel-heading"><div><p className="eyebrow">BLOCK PIPELINE</p><h2>Requests in motion</h2></div><button className="text-button" onClick={() => navigate('/department/block-requests')}>View all</button></div>{blocks.slice(0, 3).map((block) => <div className="department-list-row" key={block.id}><div><strong>{block.id}</strong><span>{block.corridor} · {block.window}</span></div><StatusBadge tone={String(block.status).toLowerCase().includes('pending') ? 'high' : 'neutral'}>{block.status}</StatusBadge></div>)}</section></div></>
}
