import { useState } from 'react'
import { CalendarClock, Plus } from 'lucide-react'
import { AlertPanel } from '../../components/common/AlertPanel'
import { ApprovalCard } from '../../components/common/ApprovalCard'
import { DepartmentBadge } from '../../components/common/DepartmentBadge'
import { DetailDrawer } from '../../components/common/DetailDrawer'
import { PageHeader } from '../../components/common/PageHeader'
import { useDepartmentWorkspace } from '../../hooks/useDepartmentWorkspace'
import { BlockRequestDrawer } from './BlockRequestDrawer'

const blankForm = { corridor: '', window: '', requestedFor: '', impact: '' }
export function DepartmentBlocksPage() { const { blocks, department, isMock, createBlock, refresh } = useDepartmentWorkspace(); const [selected, setSelected] = useState(null); const [open, setOpen] = useState(false); const [form, setForm] = useState(blankForm); const [message, setMessage] = useState('')
  function update(field, value) { setForm((current) => ({ ...current, [field]: value })) }
  async function submit(event) { event.preventDefault(); await createBlock({ ...form, department }); setMessage('Block request saved as a draft.'); setForm(blankForm); setOpen(false); refresh() }
  return <><PageHeader eyebrow={`${department} / BLOCK PLANNING`} title="Block requests" description="Prepare maintenance windows for department review and coordination." actions={<button className="primary-button" onClick={() => setOpen(true)}><Plus size={16} /> Create request</button>} />{isMock && <AlertPanel tone="info" title="Draft requests are in demo mode" description="Block creation uses the temporary department mock service until the backend block contract is connected." />}{message && <AlertPanel tone="info" title="Request created" description={message} />}{blocks.length ? <div className="approval-grid">{blocks.map((block) => <ApprovalCard key={block.id} title={`${block.corridor} · ${block.window}`} requestId={block.id} department={block.department} priority={block.status === 'Pending review' ? 'High' : 'Medium'} submittedAt={block.requestedFor} status={block.status} onReview={() => setSelected(block)} />)}</div> : <div className="state-panel">No block requests for {department}.</div>}<BlockRequestDrawer block={selected} onClose={() => setSelected(null)} /><DetailDrawer open={open} title="Create maintenance block request" onClose={() => setOpen(false)}><form className="drawer-form" onSubmit={submit}><label>Corridor<input required value={form.corridor} onChange={(event) => update('corridor', event.target.value)} placeholder="e.g. ALD-CNB" /></label><label>Requested window<input required value={form.window} onChange={(event) => update('window', event.target.value)} placeholder="e.g. 22:40-00:10" /></label><label>Maintenance work<input required value={form.requestedFor} onChange={(event) => update('requestedFor', event.target.value)} placeholder="Describe the planned work" /></label><label>Operational impact<input required value={form.impact} onChange={(event) => update('impact', event.target.value)} placeholder="Known impact or train paths" /></label><div className="drawer-form-note"><CalendarClock size={15} /> <span><DepartmentBadge department={department} /> This request is scoped to the current department.</span></div><button className="primary-button" type="submit">Save draft request</button></form></DetailDrawer></> }
