import { Check, RotateCcw, X } from 'lucide-react'
import { useState } from 'react'
import { AlertPanel } from '../../components/common/AlertPanel'
import { DepartmentBadge } from '../../components/common/DepartmentBadge'
import { DetailDrawer } from '../../components/common/DetailDrawer'
import { PageHeader } from '../../components/common/PageHeader'
import { PriorityBadge } from '../../components/common/PriorityBadge'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useDepartmentOfficerWorkspace } from '../../hooks/useDepartmentOfficerWorkspace'

export function DepartmentOfficerApprovalsPage() { const { requests, isMock, decide } = useDepartmentOfficerWorkspace(); const [selected, setSelected] = useState(null); const [message, setMessage] = useState(''); const [working, setWorking] = useState(false)
  async function act(action) { setWorking(true); try { const result = await decide(selected.id, action); setMessage(`${result.status} recorded for ${selected.id}.`); setSelected(null) } catch (error) { setMessage(error.message) } finally { setWorking(false) } }
  return <><PageHeader eyebrow="DEPARTMENT DECISION DESK / APPROVALS" title="Department approvals" description="Make department-level decisions before requests move into operations feasibility review." actions={<StatusBadge tone="demo">Prototype actions</StatusBadge>} />{isMock && <AlertPanel tone="info" title="Department approval actions are prototype-only" description="No department approval endpoint is defined in the current frontend API layer." />}{message && <AlertPanel tone="info" title="Decision update" description={message} />}{requests.filter((request) => request.status === 'Pending review').map((request) => <article className="department-approval-row" key={request.id}><div><span>{request.id}</span><h2>{request.title}</h2><p>{request.section} · {request.submittedBy}</p></div><DepartmentBadge department={request.department} /><PriorityBadge value={request.priority} /><button className="text-button" onClick={() => setSelected(request)}>Review</button></article>)}<DetailDrawer open={Boolean(selected)} title={`Review ${selected?.id ?? 'request'}`} onClose={() => setSelected(null)}>{selected && <div className="approval-detail"><div className="detail-badges"><DepartmentBadge department={selected.department} /><PriorityBadge value={selected.priority} /><StatusBadge tone="high">{selected.status}</StatusBadge></div><dl className="detail-list"><div><dt>Affected section</dt><dd>{selected.section}</dd></div><div><dt>Submitted by</dt><dd>{selected.submittedBy}</dd></div><div><dt>Submitted at</dt><dd>{selected.submittedAt}</dd></div></dl><AlertPanel tone="warning" title="Planner request requires review" description="Confirm the department scope and request readiness before approving." /><div className="approval-actions"><button className="secondary-button" disabled={working} onClick={() => act('request_changes')}><RotateCcw size={15} /> Request changes</button><button className="secondary-button" disabled={working} onClick={() => act('reject')}><X size={15} /> Reject</button><button className="primary-button" disabled={working} onClick={() => act('approve')}><Check size={15} /> Approve request</button></div></div>}</DetailDrawer></> }
