import { AlertTriangle, CheckCircle2, ClipboardCheck, Clock3, FileClock } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AlertPanel } from '../../components/common/AlertPanel'
import { KpiCard } from '../../components/common/KpiCard'
import { PageHeader } from '../../components/common/PageHeader'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useDepartmentOfficerWorkspace } from '../../hooks/useDepartmentOfficerWorkspace'

export function DepartmentOfficerHomePage() { const { requests, performance, isMock } = useDepartmentOfficerWorkspace(); const navigate = useNavigate(); const pending = requests.filter((request) => request.status === 'Pending review'); const critical = requests.filter((request) => request.priority === 'Critical'); const overdue = performance.reduce((total, item) => total + item.overdue, 0); return <><PageHeader eyebrow="DEPARTMENT DECISION DESK" title="Review department readiness" description="Decide which planner requests are ready to move into operations feasibility review." actions={<button className="primary-button" onClick={() => navigate('/department-officer/approvals')}><ClipboardCheck size={16} /> Open approvals</button>} />{isMock && <AlertPanel tone="info" title="Department officer prototype data" description="Requests and performance values are isolated demo fixtures until department approval contracts are available." />}<div className="kpi-grid officer-kpis"><KpiCard label="Pending requests" value={pending.length} detail="Needs review" tone="amber" icon={FileClock} /><KpiCard label="Critical requests" value={critical.length} detail="Priority decision" tone="red" icon={AlertTriangle} /><KpiCard label="Overdue department tasks" value={overdue} detail="Escalation signal" tone="red" icon={Clock3} /><KpiCard label="Ready departments" value={performance.filter((item) => item.readiness === 'Ready for review').length} detail="Planner readiness" tone="green" icon={CheckCircle2} /></div><div className="officer-decision-grid"><section className="executive-panel"><div className="executive-panel-head"><div><p className="eyebrow">DECISION QUEUE</p><h2>Requests awaiting review</h2></div><button className="text-button" onClick={() => navigate('/department-officer/requests')}>View all</button></div>{pending.slice(0, 3).map((request) => <div className="officer-queue-row" key={request.id}><div><strong>{request.id} · {request.title}</strong><span>{request.department} · {request.section}</span></div><StatusBadge tone={request.priority === 'Critical' ? 'critical' : 'high'}>{request.priority}</StatusBadge></div>)}</section><section className="executive-panel decision-panel department-decision-panel"><div className="executive-panel-head"><div><p className="eyebrow">AUTHORITY</p><h2>Department approval gate</h2></div></div><p>Approve, reject, or return planner requests before operations evaluates train and corridor feasibility.</p><button className="primary-button" onClick={() => navigate('/department-officer/approvals')}>Review decisions</button></section></div></> }
