// Temporary admin fixtures. No admin API contracts currently exist in the frontend API layer.
const users = [{ id: 'USR-001', name: 'Engineering Planner', email: 'engineering.planner@railyukti.demo', role: 'DEPARTMENT_PLANNER', department: 'ENGINEERING', status: 'Active', lastSeen: 'Today, 09:42' }, { id: 'USR-002', name: 'Operations Planner', email: 'operations.planner@railyukti.demo', role: 'OPERATIONS_PLANNER', department: 'OPERATING', status: 'Active', lastSeen: 'Today, 09:38' }, { id: 'USR-003', name: 'Field Supervisor', email: 'field.supervisor@railyukti.demo', role: 'FIELD_SUPERVISOR', department: 'TRD', status: 'Invited', lastSeen: 'Never' }]
const roles = [{ id: 'ROLE-01', name: 'FIELD_SUPERVISOR', permissions: 6, users: 18, status: 'Active' }, { id: 'ROLE-02', name: 'DEPARTMENT_PLANNER', permissions: 8, users: 12, status: 'Active' }, { id: 'ROLE-03', name: 'ADMIN', permissions: 24, users: 3, status: 'Active' }]
const departments = [{ id: 'DEPT-01', name: 'ENGINEERING', sections: 12, users: 44, assets: 820, status: 'Active' }, { id: 'DEPT-02', name: 'TRD', sections: 9, users: 36, assets: 610, status: 'Active' }, { id: 'DEPT-03', name: 'S&T', sections: 7, users: 29, assets: 402, status: 'Active' }, { id: 'DEPT-04', name: 'OPERATING', sections: 8, users: 31, assets: 0, status: 'Active' }]
const sections = [{ id: 'SEC-01', code: 'ALD-CNB', department: 'ENGINEERING', assets: 182, status: 'Active' }, { id: 'SEC-02', code: 'NDLS-GZB', department: 'TRD', assets: 137, status: 'Active' }, { id: 'SEC-03', code: 'NDLS YARD', department: 'S&T', assets: 84, status: 'Active' }]
const assets = [{ id: 'AST-001', code: 'OHE-M14-07', type: 'OHE Mast', department: 'TRD', section: 'ALD-CNB', criticality: 'Critical', status: 'Operational' }, { id: 'AST-002', code: 'BR-112A', type: 'Bridge', department: 'ENGINEERING', section: 'GZB-MTC', criticality: 'High', status: 'Inspection due' }, { id: 'AST-003', code: 'RR-B12', type: 'Relay Room', department: 'S&T', section: 'NDLS YARD', criticality: 'Critical', status: 'Maintenance due' }]
const configuration = [{ id: 'CFG-01', key: 'TIMETABLE_SYNC_INTERVAL', value: '15 minutes', category: 'Integrations', status: 'Configured' }, { id: 'CFG-02', key: 'DEFAULT_DIVISION', value: 'Delhi Division', category: 'System', status: 'Configured' }, { id: 'CFG-03', key: 'AUDIT_RETENTION', value: '365 days', category: 'Governance', status: 'Configured' }]
const auditLogs = [{ id: 'AUD-1008', time: '09:42', actor: 'System Admin', action: 'Updated role permissions', target: 'DEPARTMENT_PLANNER', result: 'Success' }, { id: 'AUD-1007', time: '09:31', actor: 'System Admin', action: 'Invited user', target: 'field.supervisor@railyukti.demo', result: 'Success' }, { id: 'AUD-1006', time: '09:04', actor: 'System Admin', action: 'Changed configuration', target: 'TIMETABLE_SYNC_INTERVAL', result: 'Success' }]
const health = [{ name: 'API gateway', status: 'Operational', latency: 'Not provided' }, { name: 'Timetable integration', status: 'Not configured', latency: 'Not provided' }, { name: 'Optimization engine', status: 'Not configured', latency: 'Not provided' }, { name: 'Audit pipeline', status: 'Operational', latency: 'Not provided' }]
export const adminMockService = { async getUsers() { return users }, async getRoles() { return roles }, async getDepartments() { return departments }, async getSections() { return sections }, async getAssets() { return assets }, async getConfiguration() { return configuration }, async getAuditLogs() { return auditLogs }, async getHealth() { return health }, async save(resource, payload) { return { id: `DEMO-${Date.now()}`, ...payload, status: 'Saved in prototype' } } }
