// Temporary executive fixtures. Backend analytics/planning and approval contracts should replace these values.
const summary = { assetAvailability: '86%', blockUtilization: 'Not provided', criticalTasks: 7, pendingApprovals: 3, operationalConflicts: 2, scheduledTasks: 18 }
const departments = [{ department: 'ENGINEERING', readiness: 'Review required', tasks: 8, critical: 3, blockStatus: '1 proposed block' }, { department: 'TRD', readiness: 'Ready for review', tasks: 6, critical: 2, blockStatus: '1 proposed block' }, { department: 'S&T', readiness: 'Ready for review', tasks: 4, critical: 1, blockStatus: '1 proposed block' }]
const weekly = [{ id: 'W37-01', date: '2026-09-08', section: 'ALD-CNB', departments: ['TRD'], tasks: ['TRD-2408', 'TRD-2387'], window: '01:15-03:00', status: 'Proposed', conflicts: 0, warnings: ['Utilization not returned by backend'] }, { id: 'W37-02', date: '2026-09-08', section: 'GZB-MTC', departments: ['ENGINEERING'], tasks: ['ENG-2410'], window: '03:15-04:30', status: 'Needs review', conflicts: 1, warnings: ['Train constraint requires review'] }, { id: 'W37-03', date: '2026-09-08', section: 'NDLS Yard', departments: ['S&T'], tasks: ['ST-2412'], window: '00:40-01:20', status: 'Proposed', conflicts: 0, warnings: [] }]
const monthly = [{ id: 'M09-01', month: 'September 2026', corridor: 'Delhi Division north', blocks: 12, departments: ['ENGINEERING', 'TRD', 'S&T'], status: 'Draft' }, { id: 'M09-02', month: 'September 2026', corridor: 'Delhi Division east', blocks: 8, departments: ['TRD', 'S&T'], status: 'Draft' }]
const approvals = weekly.map((block) => ({ ...block, affectedSections: [block.section], departmentsInvolved: block.departments, scheduledTasks: block.tasks, blockWindow: block.window, optimizationMetrics: {}, warnings: block.warnings }))
const performance = [{ department: 'ENGINEERING', completion: 'Not provided', overdue: 3, conflicts: 1, trend: 'Review required' }, { department: 'TRD', completion: 'Not provided', overdue: 2, conflicts: 0, trend: 'Stable' }, { department: 'S&T', completion: 'Not provided', overdue: 1, conflicts: 0, trend: 'Stable' }]
const analytics = { trend: [{ label: 'Week 34', value: 12 }, { label: 'Week 35', value: 15 }, { label: 'Week 36', value: 16 }, { label: 'Week 37', value: 18 }], notes: ['Cross-department plan is ready for review', 'Two operational conflicts require attention'] }
export const divisionalMockService = { async getSummary() { return summary }, async getDepartments() { return departments }, async getWeekly() { return weekly }, async getMonthly() { return monthly }, async getApprovals() { return approvals }, async getPerformance() { return performance }, async getAnalytics() { return analytics }, async actOnPlan(id, action) { return { id, action, status: action === 'approve' ? 'Approved' : 'Changes requested', source: 'Prototype approval action' } } }
