// Temporary COA fixtures. Replace with timetable, corridor and conflict contracts when available.
const trains = [
  { id: 'TR-12301', trainNumber: '12301 Rajdhani', section: 'NDLS-GZB', date: '2026-09-07', arrival: '22:35', departure: '22:52', direction: 'Down', timelineStart: 1355, timelineEnd: 1372, state: 'Scheduled' },
  { id: 'TR-12423', trainNumber: '12423 DLI-DBRG', section: 'NDLS-GZB', date: '2026-09-07', arrival: '00:18', departure: '00:31', direction: 'Down', timelineStart: 18, timelineEnd: 31, state: 'Scheduled' },
  { id: 'TR-12002', trainNumber: '12002 Shatabdi', section: 'NDLS-ALD', date: '2026-09-07', arrival: '06:00', departure: '06:10', direction: 'Down', timelineStart: 360, timelineEnd: 370, state: 'Scheduled' },
  { id: 'TR-12952', trainNumber: '12952 Mumbai Rajdhani', section: 'GZB-NDLS', date: '2026-09-07', arrival: '04:45', departure: '05:02', direction: 'Up', timelineStart: 285, timelineEnd: 302, state: 'Delayed' },
]
const corridors = [{ id: 'COR-01', name: 'NDLS-GZB', occupied: true, periods: [{ start: 18, end: 31, label: '12423 DLI-DBRG', type: 'train' }, { start: 285, end: 302, label: '12952 Mumbai Rajdhani', type: 'train' }, { start: 1355, end: 1372, label: '12301 Rajdhani', type: 'train' }], windows: [{ start: 1360, end: 1420, label: 'Proposed maintenance', type: 'proposed' }, { start: 1440, end: 1500, label: 'Available', type: 'available' }] }, { id: 'COR-02', name: 'ALD-CNB', occupied: false, periods: [{ start: 360, end: 370, label: '12002 Shatabdi', type: 'train' }], windows: [{ start: 600, end: 720, label: 'Available', type: 'available' }] }]
const blocks = [{ id: 'BR-108', section: 'NDLS-GZB', date: '2026-09-07', start: '22:40', end: '00:10', duration: '01h 30m', status: 'Proposed', purpose: 'OHE inspection', corridor: 'NDLS-GZB' }, { id: 'BR-105', section: 'ALD-CNB', date: '2026-09-08', start: '01:15', end: '03:00', duration: '01h 45m', status: 'Available', purpose: 'Bridge inspection', corridor: 'ALD-CNB' }, { id: 'BR-101', section: 'BPL-ETW', date: '2026-09-08', start: '11:30', end: '12:15', duration: '45m', status: 'Conflict', purpose: 'TRD maintenance', corridor: 'BPL-ETW' }]
const conflicts = [{ id: 'CF-01', severity: 'Critical', section: 'NDLS-GZB', blockId: 'BR-108', trainNumber: '12301 Rajdhani', window: '22:40-00:10', issue: 'Proposed window overlaps scheduled train path', action: 'Move block after 00:35' }, { id: 'CF-02', severity: 'High', section: 'BPL-ETW', blockId: 'BR-101', trainNumber: '12002 Shatabdi', window: '11:30-12:15', issue: 'Recovery margin below operational threshold', action: 'Review alternate window' }]
const alerts = [{ id: 'AL-01', tone: 'critical', title: 'Night window at risk', description: 'BR-108 overlaps the Rajdhani path on NDLS-GZB.' }, { id: 'AL-02', tone: 'warning', title: 'Corridor occupancy elevated', description: 'NDLS-GZB has limited clear time before midnight.' }]
export const operationsMockService = { async getTrains() { return trains }, async getBlocks() { return blocks }, async getCorridors() { return corridors }, async getConflicts() { return conflicts }, async getAlerts() { return alerts } }
