import { useState } from 'react'
import { AlertTriangle, CheckCircle2 } from 'lucide-react'
import { PageHeader } from '../../components/common/PageHeader'
import { AlertPanel } from '../../components/common/AlertPanel'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useFieldWorkspace } from '../../hooks/useFieldWorkspace'
import { fieldMockService } from '../../services/fieldMockService'

const initialForm = { assetCode: '', defectType: '', severity: 'Medium', description: '', observedAt: '' }
export function FieldDefectsPage() { const { assets, isMock } = useFieldWorkspace(); const [form, setForm] = useState(initialForm); const [submitted, setSubmitted] = useState(null); const [saving, setSaving] = useState(false)
  function update(field, value) { setForm((current) => ({ ...current, [field]: value })) }
  async function submit(event) { event.preventDefault(); setSaving(true); const result = await fieldMockService.submitDefect(form); setSubmitted(result); setForm(initialForm); setSaving(false) }
  return <><PageHeader eyebrow="FIELD OPERATIONS / DEFECTS" title="Report a defect" description="Capture an issue against an assigned asset for planner review and follow-up." actions={<StatusBadge tone="demo">Demo submission</StatusBadge>} />{!isMock && <AlertPanel tone="info" title="Defect submission endpoint pending" description="The backend contract for defect creation is not available yet. This form is isolated to the temporary mock service and will be replaced without changing the page workflow." />}{submitted && <AlertPanel tone="info" title="Defect captured in demo mode" description={`Reference ${submitted.id}. Replace the mock service when the defect endpoint is available.`} action={<CheckCircle2 size={18} />} />}<form className="defect-form" onSubmit={submit}><div className="form-section"><div className="form-section-heading"><AlertTriangle size={18} /><div><h2>Defect details</h2><p>Use the asset and severity information available from the current field context.</p></div></div><div className="form-grid"><label>Asset<select required value={form.assetCode} onChange={(event) => update('assetCode', event.target.value)}><option value="">Select assigned asset</option>{assets.map((asset) => <option value={asset.id} key={asset.id}>{asset.id} · {asset.type}</option>)}</select></label><label>Defect type<select required value={form.defectType} onChange={(event) => update('defectType', event.target.value)}><option value="">Select defect type</option><option>Safety concern</option><option>Equipment failure</option><option>Damage or obstruction</option><option>Abnormal condition</option></select></label><label>Severity<select value={form.severity} onChange={(event) => update('severity', event.target.value)}><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select></label><label>Observed at<input required type="datetime-local" value={form.observedAt} onChange={(event) => update('observedAt', event.target.value)} /></label><label className="form-full">Description<textarea required rows="5" value={form.description} onChange={(event) => update('description', event.target.value)} placeholder="Describe what you observed, where it is, and any immediate safety action taken." /></label></div></div><div className="form-actions"><button className="secondary-button" type="button" onClick={() => setForm(initialForm)}>Clear</button><button className="primary-button" type="submit" disabled={saving}>{saving ? 'Submitting...' : 'Submit defect report'}</button></div></form></> }
