import { AlertTriangle, CheckCircle2, ClipboardCheck, Clock3, ShieldAlert, Wrench } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertPanel } from '../../components/common/AlertPanel'
import { KpiCard } from '../../components/common/KpiCard'
import { PageHeader } from '../../components/common/PageHeader'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useFieldWorkspace } from '../../hooks/useFieldWorkspace'
import { FieldTaskTable } from '../../components/maintenance/FieldTaskTable'
import { FieldTaskDrawer } from './FieldTaskDrawer'
import { fieldValue } from '../../utils/fieldFormatters'

const today = '2026-09-07'
function isDueToday(task) { return fieldValue(task, 'dueDate', 'due') === today }
function isOverdue(task) { return String(fieldValue(task, 'status')).toLowerCase().includes('overdue') || fieldValue(task, 'dueDate') < today }
function isCritical(task) { return ['critical', 'high'].includes(String(fieldValue(task, 'priority')).toLowerCase()) }

export function FieldHomePage() {
  const { tasks, assets, error, isMock, refresh, updateTask } = useFieldWorkspace(); const navigate = useNavigate(); const [selectedTask, setSelectedTask] = useState(null); const [message, setMessage] = useState('')
  const pending = tasks.filter((task) => !String(fieldValue(task, 'status')).toLowerCase().includes('completed')); const critical = tasks.filter(isCritical); const overdue = tasks.filter(isOverdue); const dueToday = tasks.filter(isDueToday); const completed = tasks.filter((task) => String(fieldValue(task, 'status')).toLowerCase().includes('completed')).slice(0, 3); const assetAlerts = assets.filter((asset) => ['critical', 'at risk'].some((term) => String(asset.criticality ?? asset.status).toLowerCase().includes(term)))
  async function handleStatusUpdate(task, nextStatus) { if (isMock) { setMessage(`Demo update saved for ${fieldValue(task, 'id', 'taskId')}.`); return } await updateTask(fieldValue(task, 'id', 'taskId'), { status: nextStatus }); refresh() }
  return <><PageHeader eyebrow="FIELD OPERATIONS" title="Good morning, field team" description="Prioritize the work that protects asset availability across your assigned section." actions={<button className="primary-button" onClick={() => navigate('/field/defects')}><AlertTriangle size={16} /> Report defect</button>} />{isMock && <AlertPanel tone="info" title="Demo data is active" description="Maintenance and asset endpoints are not configured, so this workspace is using isolated field mock data until the backend contract is available." />}{error && !isMock && <AlertPanel tone="warning" title="Live data unavailable" description={error.message} action={<button className="text-button" onClick={refresh}>Retry</button>} />}<div className="kpi-grid field-kpis"><KpiCard label="My pending tasks" value={pending.length} detail="Assigned to you" tone="blue" icon={ClipboardCheck} /><KpiCard label="Critical tasks" value={critical.length} detail="Needs attention" tone="red" icon={ShieldAlert} /><KpiCard label="Overdue tasks" value={overdue.length} detail="Resolve today" tone="amber" icon={Clock3} /><KpiCard label="Due today" value={dueToday.length} detail="Before end of shift" tone="green" icon={CheckCircle2} /></div><div className="field-dashboard-grid"><section className="field-panel"><div className="panel-heading"><div><p className="eyebrow">MY WORKLIST</p><h2>Pending maintenance tasks</h2></div><button className="text-button" onClick={() => navigate('/field/tasks')}>View all <Wrench size={15} /></button></div><FieldTaskTable tasks={pending.slice(0, 4)} onSelect={setSelectedTask} /></section><section className="field-side-stack"><section className="field-panel"><div className="panel-heading"><div><p className="eyebrow">ASSET WATCH</p><h2>Critical asset alerts</h2></div><ShieldAlert size={18} className="section-icon critical" /></div>{assetAlerts.length ? assetAlerts.map((asset) => <div className="asset-alert-row" key={asset.id}><div><strong>{asset.id}</strong><span>{asset.type} · {asset.section}</span></div><StatusBadge tone="critical">{asset.status}</StatusBadge></div>) : <p className="panel-muted">No critical asset alerts.</p>}</section><section className="field-panel"><div className="panel-heading"><div><p className="eyebrow">RECENTLY COMPLETED</p><h2>Closed work</h2></div><CheckCircle2 size={18} className="section-icon success" /></div>{completed.length ? completed.map((task) => <div className="completed-row" key={fieldValue(task, 'id', 'taskId')}><span><CheckCircle2 size={15} />{fieldValue(task, 'asset')}</span><small>{fieldValue(task, 'dueDate', 'due')}</small></div>) : <p className="panel-muted">No recently completed work.</p>}</section></section></div><FieldTaskDrawer task={selectedTask} onClose={() => setSelectedTask(null)} onStatusUpdate={handleStatusUpdate} />{message && <div className="toast-message">{message}</div>}</>
}
