import { useState } from 'react'
import { PageHeader } from '../../components/common/PageHeader'
import { DataTable } from '../../components/common/DataTable'
import { DepartmentBadge } from '../../components/common/DepartmentBadge'
import { PriorityBadge } from '../../components/common/PriorityBadge'
import { StatusBadge } from '../../components/common/StatusBadge'
import { DetailDrawer } from '../../components/common/DetailDrawer'
import { AlertPanel } from '../../components/common/AlertPanel'
import { useFieldWorkspace } from '../../hooks/useFieldWorkspace'

export function FieldAssetsPage() { const { assets, loading, error, isMock, refresh } = useFieldWorkspace(); const [selected, setSelected] = useState(null); const columns = [{ key: 'id', label: 'Asset code' }, { key: 'type', label: 'Asset type' }, { key: 'department', label: 'Department', render: (row) => <DepartmentBadge department={row.department} /> }, { key: 'section', label: 'Section' }, { key: 'criticality', label: 'Criticality', render: (row) => <PriorityBadge value={row.criticality} /> }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone={String(row.status).toLowerCase().includes('risk') ? 'critical' : 'low'}>{row.status}</StatusBadge> }, { key: 'action', label: 'Action', render: (row) => <button className="text-button" onClick={() => setSelected(row)}>View details</button> }]
  return <><PageHeader eyebrow="FIELD OPERATIONS / ASSETS" title="Assigned assets" description="Inspect asset condition and maintenance context for your working section." actions={<StatusBadge tone={isMock ? 'demo' : 'low'}>{isMock ? 'Demo data' : 'Live API'}</StatusBadge>} />{error && !isMock && <AlertPanel tone="warning" title="Asset data could not be loaded" description={error.message} action={<button className="text-button" onClick={refresh}>Retry</button>} />}{loading ? <div className="state-panel">Loading assigned assets...</div> : <DataTable columns={columns} rows={assets} emptyMessage="No assets are assigned to this section." />}<DetailDrawer open={Boolean(selected)} title={selected?.id ?? 'Asset details'} onClose={() => setSelected(null)}>{selected && <dl className="detail-list"><div><dt>Asset type</dt><dd>{selected.type}</dd></div><div><dt>Department</dt><dd><DepartmentBadge department={selected.department} /></dd></div><div><dt>Section</dt><dd>{selected.section}</dd></div><div><dt>Criticality</dt><dd><PriorityBadge value={selected.criticality} /></dd></div><div><dt>Status</dt><dd>{selected.status}</dd></div><div><dt>Last maintenance</dt><dd>{selected.lastMaintenance}</dd></div><div><dt>Next maintenance</dt><dd>{selected.nextMaintenance}</dd></div></dl>}</DetailDrawer></> }
