import { useState } from 'react'
import { Check, RotateCcw } from 'lucide-react'
import { AlertPanel } from '../../components/common/AlertPanel'
import { ApprovalCard } from '../../components/common/ApprovalCard'
import { DepartmentBadge } from '../../components/common/DepartmentBadge'
import { DetailDrawer } from '../../components/common/DetailDrawer'
import { PageHeader } from '../../components/common/PageHeader'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useDivisionalWorkspace } from '../../hooks/useDivisionalWorkspace'

export function OfficerApprovalPage() { const { approvals, isMock, error, refresh, actOnPlan } = useDivisionalWorkspace(); const [selected, setSelected] = useState(null); const [message, setMessage] = useState(''); const [working, setWorking] = useState(false)
  async function act(action) { setWorking(true); try { const result = await actOnPlan(selected.id, action); setMessage(`${result.status} recorded for ${selected.id}.`); setSelected(null) } catch (actionError) { setMessage(actionError.message) } finally { setWorking(false) } }
  return <><PageHeader eyebrow="DIVISION CONTROL / APPROVAL CENTER" title="Approval center" description="Inspect risk, coordination and operational constraints before approving the proposed plan." actions={<StatusBadge tone={isMock ? 'demo' : 'low'}>{isMock ? 'Prototype actions' : 'Backend approval state'}</StatusBadge>} />{isMock && <AlertPanel tone="info" title="Approval actions are prototype-only" description="No backend approval endpoint is defined in the current API layer. Review details are available, but actions are clearly labeled demo results." />}{error && !isMock && <AlertPanel tone="warning" title="Approval data unavailable" description={error.message} action={<button className="text-button" onClick={refresh}>Retry</button>} />}{message && <AlertPanel tone="info" title="Decision update" description={message} />}{approvals.length ? <div className="approval-grid">{approvals.map((item) => <ApprovalCard key={item.id} title={`${item.section} · ${item.window}`} requestId={item.id} department={item.departments?.[0]} priority={item.conflicts ? 'Critical' : 'Medium'} submittedAt={item.date} status={item.status} onReview={() => setSelected(item)} />)}</div> : <div className="state-panel">No proposed plans require approval.</div>}<DetailDrawer open={Boolean(selected)} title={`Review ${selected?.id ?? 'plan'}`} onClose={() => setSelected(null)}>{selected && <div className="approval-detail"><div className="detail-badges">{selected.departmentsInvolved?.map((department) => <DepartmentBadge key={department} department={department} />)}<StatusBadge tone={selected.conflicts ? 'critical' : 'high'}>{selected.status}</StatusBadge></div><dl className="detail-list"><div><dt>Affected sections</dt><dd>{selected.affectedSections?.join(', ') ?? 'Not provided'}</dd></div><div><dt>Scheduled tasks</dt><dd>{selected.scheduledTasks?.join(', ') ?? 'Not provided'}</dd></div><div><dt>Block window</dt><dd>{selected.blockWindow ?? 'Not provided'}</dd></div><div><dt>Operational conflicts</dt><dd>{selected.conflicts ?? 'Not provided'}</dd></div><div><dt>Optimization metrics</dt><dd>{Object.keys(selected.optimizationMetrics ?? {}).length ? JSON.stringify(selected.optimizationMetrics) : 'Not provided by backend'}</dd></div></dl>{selected.warnings?.length ? <AlertPanel tone="warning" title="Warnings" description={selected.warnings.join(' ')} /> : <AlertPanel tone="info" title="No warnings returned" description="The backend returned no warning fields for this plan." />}<div className="approval-actions"><button className="secondary-button" disabled={working} onClick={() => act('request_changes')}><RotateCcw size={15} /> Request changes</button><button className="secondary-button" disabled={working} onClick={() => act('send_back')}>Send back</button><button className="primary-button" disabled={working} onClick={() => act('approve')}><Check size={15} /> Approve plan</button></div></div>}</DetailDrawer></> }
