import { useAdminWorkspace } from '../../hooks/useAdminWorkspace'
import { AdminTablePage } from '../../components/admin/AdminTablePage'
import { DepartmentBadge } from '../../components/common/DepartmentBadge'
import { StatusBadge } from '../../components/common/StatusBadge'
import { PriorityBadge } from '../../components/common/PriorityBadge'
import { DataTable } from '../../components/common/DataTable'
import { PageHeader } from '../../components/common/PageHeader'
import { AdminSourceBanner } from '../../components/admin/AdminSourceBanner'

const userColumns = [{ key: 'id', label: 'ID' }, { key: 'name', label: 'User' }, { key: 'email', label: 'Email' }, { key: 'role', label: 'Role' }, { key: 'department', label: 'Department', render: (row) => <DepartmentBadge department={row.department} /> }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone={row.status === 'Active' ? 'low' : 'high'}>{row.status}</StatusBadge> }, { key: 'lastSeen', label: 'Last seen' }]
const roleColumns = [{ key: 'id', label: 'ID' }, { key: 'name', label: 'Role' }, { key: 'permissions', label: 'Permissions' }, { key: 'users', label: 'Users' }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone="low">{row.status}</StatusBadge> }]
const departmentColumns = [{ key: 'id', label: 'ID' }, { key: 'name', label: 'Department' }, { key: 'sections', label: 'Sections' }, { key: 'users', label: 'Users' }, { key: 'assets', label: 'Assets' }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone="low">{row.status}</StatusBadge> }]
const sectionColumns = [{ key: 'id', label: 'ID' }, { key: 'code', label: 'Section code' }, { key: 'department', label: 'Department', render: (row) => <DepartmentBadge department={row.department} /> }, { key: 'assets', label: 'Assets' }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone="low">{row.status}</StatusBadge> }]
const assetColumns = [{ key: 'id', label: 'ID' }, { key: 'code', label: 'Asset code' }, { key: 'type', label: 'Type' }, { key: 'department', label: 'Department', render: (row) => <DepartmentBadge department={row.department} /> }, { key: 'section', label: 'Section' }, { key: 'criticality', label: 'Criticality', render: (row) => <PriorityBadge value={row.criticality} /> }, { key: 'status', label: 'Status' }]
const configColumns = [{ key: 'key', label: 'Configuration key' }, { key: 'value', label: 'Value' }, { key: 'category', label: 'Category' }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone="low">{row.status}</StatusBadge> }]
const auditColumns = [{ key: 'time', label: 'Time' }, { key: 'actor', label: 'Actor' }, { key: 'action', label: 'Action' }, { key: 'target', label: 'Target' }, { key: 'result', label: 'Result', render: (row) => <StatusBadge tone="low">{row.result}</StatusBadge> }]

export function AdminUsersPage() { const { users } = useAdminWorkspace(); return <AdminTablePage eyebrow="ADMIN / IDENTITY" title="User management" description="Review demo identities and their current role and department assignments." rows={users} columns={userColumns} formTitle="Add user" formFields={[{ key: 'name', label: 'Name', required: true }, { key: 'email', label: 'Email', type: 'email', required: true }, { key: 'role', label: 'Role', type: 'select', options: ['FIELD_SUPERVISOR', 'DEPARTMENT_PLANNER', 'ADMIN'], required: true }, { key: 'department', label: 'Department', type: 'select', options: ['ENGINEERING', 'TRD', 'S&T', 'OPERATING'], required: true }]} /> }
export function AdminRolesPage() { const { roles } = useAdminWorkspace(); return <AdminTablePage eyebrow="ADMIN / AUTHORIZATION" title="Roles and permissions" description="Review configured role capacity and user assignments." rows={roles} columns={roleColumns} formTitle="Create role" formFields={[{ key: 'name', label: 'Role name', required: true }]} /> }
export function AdminDepartmentsPage() { const { departments } = useAdminWorkspace(); return <AdminTablePage eyebrow="ADMIN / ORGANIZATION" title="Department management" description="Maintain the department hierarchy used by planning and operations workflows." rows={departments} columns={departmentColumns} formTitle="Add department" formFields={[{ key: 'name', label: 'Department name', required: true }]} /> }
export function AdminSectionsPage() { const { sections } = useAdminWorkspace(); return <AdminTablePage eyebrow="ADMIN / ORGANIZATION" title="Section management" description="Review operational sections and their department ownership." rows={sections} columns={sectionColumns} formTitle="Add section" formFields={[{ key: 'code', label: 'Section code', required: true }, { key: 'department', label: 'Department', type: 'select', options: ['ENGINEERING', 'TRD', 'S&T'], required: true }]} /> }
export function AdminAssetsPage() { const { assets } = useAdminWorkspace(); return <AdminTablePage eyebrow="ADMIN / REGISTRY" title="Asset management" description="Review the central asset registry and criticality configuration." rows={assets} columns={assetColumns} formTitle="Add asset" formFields={[{ key: 'code', label: 'Asset code', required: true }, { key: 'type', label: 'Asset type', required: true }, { key: 'department', label: 'Department', type: 'select', options: ['ENGINEERING', 'TRD', 'S&T'], required: true }, { key: 'section', label: 'Section', required: true }]} /> }
export function AdminConfigurationPage() { const { configuration } = useAdminWorkspace(); return <AdminTablePage eyebrow="ADMIN / SYSTEM" title="Configuration" description="Review system settings currently represented in the prototype control plane." rows={configuration} columns={configColumns} formTitle="Add configuration" formFields={[{ key: 'key', label: 'Configuration key', required: true }, { key: 'value', label: 'Value', required: true }, { key: 'category', label: 'Category', required: true }]} /> }
export function AdminAuditLogsPage() { const { auditLogs } = useAdminWorkspace(); return <AdminTablePage eyebrow="ADMIN / GOVERNANCE" title="Audit logs" description="Review administrative actions and their recorded outcomes." rows={auditLogs} columns={auditColumns} /> }

export function AdminDataNote() { return <><PageHeader eyebrow="ADMINISTRATION" title="Admin data source" description="Admin API contracts are not currently defined." /><AdminSourceBanner /><DataTable columns={[]} rows={[]} /></> }
