import { useState } from 'react'
import { AlertPanel } from '../../components/common/AlertPanel'
import { DataTable } from '../../components/common/DataTable'
import { PageHeader } from '../../components/common/PageHeader'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useOperationsWorkspace } from '../../hooks/useOperationsWorkspace'
import { BlockDetailsDrawer } from './BlockDetailsDrawer'

export function OperationsBlocksPage() { const { blocks, isMock, error, refresh } = useOperationsWorkspace(); const [selected, setSelected] = useState(null); const available = blocks.filter((block) => String(block.status).toLowerCase().includes('available')); const proposed = blocks.filter((block) => !String(block.status).toLowerCase().includes('available')); const columns = [{ key: 'section', label: 'Section' }, { key: 'date', label: 'Date' }, { key: 'start', label: 'Start' }, { key: 'end', label: 'End' }, { key: 'duration', label: 'Duration' }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone={String(row.status).toLowerCase().includes('conflict') ? 'critical' : String(row.status).toLowerCase().includes('available') ? 'low' : 'high'}>{row.status}</StatusBadge> }, { key: 'utilization', label: 'Utilization', render: (row) => row.utilization ?? row.utilisation ?? 'Not provided' }, { key: 'action', label: 'Action', render: (row) => <button className="text-button" onClick={() => setSelected(row)}>Details</button> }]
  return <><PageHeader eyebrow="OPERATING / BLOCK CONTROL" title="Block availability" description="Separate confirmed windows from proposed blocks before operations review." actions={<StatusBadge tone={isMock ? 'demo' : 'low'}>{isMock ? 'Demo block data' : 'Backend block data'}</StatusBadge>} />{error && !isMock && <AlertPanel tone="warning" title="Block data unavailable" description={error.message} action={<button className="text-button" onClick={refresh}>Retry</button>} />}<section className="availability-banner"><div><p className="eyebrow">CONFIRMED AVAILABILITY</p><strong>{available.length} windows</strong><span>These windows are available in the current operations data.</span></div><div className="availability-meter"><i style={{ width: `${available.length ? Math.min(100, available.length / Math.max(blocks.length, 1) * 100) : 0}%` }} /></div></section><h2 className="operations-subheading">Proposed and reviewed blocks</h2><DataTable columns={columns} rows={proposed} emptyMessage="No proposed blocks returned." /><BlockDetailsDrawer block={selected} onClose={() => setSelected(null)} /></> }
