import { useState } from 'react'
import { AlertPanel } from '../../components/common/AlertPanel'
import { PageHeader } from '../../components/common/PageHeader'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useOperationsWorkspace } from '../../hooks/useOperationsWorkspace'
import { CorridorTimeline } from '../../components/trains/CorridorTimeline'
import { DetailDrawer } from '../../components/common/DetailDrawer'

export function OperationsCorridorPage() { const { corridors, isMock, error, refresh } = useOperationsWorkspace(); const [selected, setSelected] = useState(null); return <><PageHeader eyebrow="OPERATING / CORRIDOR CONTROL" title="Corridor availability" description="Compare movement paths, occupied periods, confirmed windows and proposed maintenance blocks." actions={<StatusBadge tone={isMock ? 'demo' : 'low'}>{isMock ? 'Demo corridor data' : 'Backend availability'}</StatusBadge>} />{isMock && <AlertPanel tone="info" title="Confirmed and proposed periods are separated" description="Green periods are confirmed available in the demo fixture. Amber periods are proposed maintenance windows and still require operational review." />}{error && !isMock && <AlertPanel tone="warning" title="Corridor availability unavailable" description={error.message} action={<button className="text-button" onClick={refresh}>Retry</button>} />}<div className="corridor-stack">{corridors.length ? corridors.map((corridor) => <CorridorTimeline key={corridor.id} corridor={corridor} onSelect={setSelected} />) : <div className="state-panel">No corridor timeline data returned by the backend.</div>}</div><DetailDrawer open={Boolean(selected)} title={selected?.label ?? 'Corridor period'} onClose={() => setSelected(null)}>{selected && <dl className="detail-list"><div><dt>Period</dt><dd>{selected.start}-{selected.end}</dd></div><div><dt>Classification</dt><dd>{selected.type === 'available' ? 'Confirmed available' : selected.type === 'proposed' ? 'Proposed maintenance' : 'Train movement'}</dd></div></dl>}</DetailDrawer></> }
