import { AlertTriangle, Blocks, CalendarClock, Gauge, TrainFront, Waypoints } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AlertPanel } from '../../components/common/AlertPanel'
import { KpiCard } from '../../components/common/KpiCard'
import { PageHeader } from '../../components/common/PageHeader'
import { StatusBadge } from '../../components/common/StatusBadge'
import { useOperationsWorkspace } from '../../hooks/useOperationsWorkspace'
import { CorridorTimeline } from '../../components/trains/CorridorTimeline'

export function OperationsHomePage() { const { trains, blocks, corridors, conflicts, alerts, isMock, error, refresh } = useOperationsWorkspace(); const navigate = useNavigate(); const available = blocks.filter((block) => String(block.status).toLowerCase().includes('available')); const proposed = blocks.filter((block) => String(block.status).toLowerCase().includes('proposed'))
  return <><PageHeader eyebrow="OPERATING / COA" title="Protect the working timetable" description="Find feasible maintenance windows without creating unacceptable conflicts with train operations." actions={<StatusBadge tone={isMock ? 'demo' : 'low'}>{isMock ? 'Demo control data' : 'Live operations data'}</StatusBadge>} />{isMock && <AlertPanel tone="info" title="Operations demo data is active" description="Timetable, corridor and conflict fixtures are isolated until the backend contracts are connected." />}{error && !isMock && <AlertPanel tone="warning" title="Live operations data unavailable" description={error.message} action={<button className="text-button" onClick={refresh}>Retry</button>} />}<div className="kpi-grid operations-kpis"><KpiCard label="Trains today" value={trains.length} detail="Movement paths" tone="blue" icon={TrainFront} /><KpiCard label="Active corridors" value={corridors.filter((corridor) => corridor.occupied).length} detail="Occupied now" tone="amber" icon={Waypoints} /><KpiCard label="Available windows" value={available.length} detail="Confirmed availability" tone="green" icon={CalendarClock} /><KpiCard label="Proposed blocks" value={proposed.length} detail="Needs feasibility review" tone="blue" icon={Blocks} /><KpiCard label="Conflicts" value={conflicts.length} detail="Operational review" tone="red" icon={AlertTriangle} /><KpiCard label="Operational alerts" value={alerts.length} detail="Active control-room signals" tone="amber" icon={Gauge} /></div><div className="operations-dashboard-grid"><section><div className="operations-section-heading"><div><p className="eyebrow">CORRIDOR PULSE</p><h2>Today’s operating picture</h2></div><button className="text-button" onClick={() => navigate('/operations/corridor')}>Open corridor view</button></div>{corridors.slice(0, 2).map((corridor) => <CorridorTimeline key={corridor.id} corridor={corridor} />)}</section><section className="operations-alert-stack"><div className="operations-section-heading"><div><p className="eyebrow">CONTROL ROOM</p><h2>Operational alerts</h2></div></div>{alerts.length ? alerts.map((alert) => <AlertPanel key={alert.id} tone={alert.tone} title={alert.title} description={alert.description} />) : <div className="state-panel">No operational alerts returned.</div>}<button className="secondary-button full-width-button" onClick={() => navigate('/operations/conflicts')}>Review conflicts <AlertTriangle size={15} /></button></section></div></>
}
