export const PERMISSIONS = Object.freeze({ VIEW_TASKS: 'VIEW_TASKS', CREATE_TASK: 'CREATE_TASK', UPDATE_TASK: 'UPDATE_TASK', VIEW_ASSETS: 'VIEW_ASSETS', CREATE_BLOCK_REQUEST: 'CREATE_BLOCK_REQUEST', VIEW_AI_RECOMMENDATIONS: 'VIEW_AI_RECOMMENDATIONS', VIEW_TIMETABLE: 'VIEW_TIMETABLE', VIEW_BLOCK_WINDOWS: 'VIEW_BLOCK_WINDOWS', REVIEW_CONFLICTS: 'REVIEW_CONFLICTS', APPROVE_BLOCK_REQUEST: 'APPROVE_BLOCK_REQUEST', VIEW_OPTIMIZED_PLAN: 'VIEW_OPTIMIZED_PLAN', GENERATE_OPTIMIZED_PLAN: 'GENERATE_OPTIMIZED_PLAN', APPROVE_PLAN: 'APPROVE_PLAN', VIEW_ANALYTICS: 'VIEW_ANALYTICS', VIEW_DEFECTS: 'VIEW_DEFECTS', REPORT_DEFECT: 'REPORT_DEFECT', VIEW_MAINTENANCE_HISTORY: 'VIEW_MAINTENANCE_HISTORY', VIEW_REQUESTS: 'VIEW_REQUESTS', VIEW_DEPARTMENT_PERFORMANCE: 'VIEW_DEPARTMENT_PERFORMANCE', MANAGE_USERS: 'MANAGE_USERS', MANAGE_ROLES: 'MANAGE_ROLES', MANAGE_CONFIGURATION: 'MANAGE_CONFIGURATION', VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS', VIEW_DEPARTMENTS: 'VIEW_DEPARTMENTS', VIEW_SECTIONS: 'VIEW_SECTIONS' })

const all = Object.values(PERMISSIONS)
export const ROLE_PERMISSIONS = {
  FIELD_SUPERVISOR: [PERMISSIONS.VIEW_TASKS, PERMISSIONS.CREATE_TASK, PERMISSIONS.UPDATE_TASK, PERMISSIONS.VIEW_ASSETS, PERMISSIONS.VIEW_DEFECTS, PERMISSIONS.REPORT_DEFECT, PERMISSIONS.VIEW_MAINTENANCE_HISTORY],
  DEPARTMENT_PLANNER: [PERMISSIONS.VIEW_TASKS, PERMISSIONS.CREATE_TASK, PERMISSIONS.UPDATE_TASK, PERMISSIONS.VIEW_ASSETS, PERMISSIONS.CREATE_BLOCK_REQUEST, PERMISSIONS.VIEW_AI_RECOMMENDATIONS, PERMISSIONS.VIEW_OPTIMIZED_PLAN, PERMISSIONS.GENERATE_OPTIMIZED_PLAN],
  DEPARTMENT_OFFICER: [PERMISSIONS.VIEW_TASKS, PERMISSIONS.VIEW_ASSETS, PERMISSIONS.APPROVE_BLOCK_REQUEST, PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.VIEW_REQUESTS, PERMISSIONS.VIEW_DEPARTMENT_PERFORMANCE],
  OPERATIONS_PLANNER: [PERMISSIONS.VIEW_TIMETABLE, PERMISSIONS.VIEW_BLOCK_WINDOWS, PERMISSIONS.REVIEW_CONFLICTS, PERMISSIONS.VIEW_ASSETS],
  DIVISIONAL_OFFICER: [PERMISSIONS.VIEW_TASKS, PERMISSIONS.VIEW_ASSETS, PERMISSIONS.VIEW_OPTIMIZED_PLAN, PERMISSIONS.GENERATE_OPTIMIZED_PLAN, PERMISSIONS.APPROVE_PLAN, PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.VIEW_DEPARTMENT_PERFORMANCE],
  ADMIN: all,
}

export function hasPermission(role, permission) { return ROLE_PERMISSIONS[role]?.includes(permission) ?? false }
export function hasAnyPermission(role, permissions = []) { return permissions.length === 0 || permissions.some((permission) => hasPermission(role, permission)) }
